"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Suspense, useEffect, useState } from "react";
import TrustStrip from "@/components/TrustStrip";

type Confirmation = { orderId: string; orderStatus: "pending_payment" | "paid" | "payment_failed" | "cancelled"; paymentStatus: "PENDING" | "COMPLETED" | "FAILED" | "CANCELLED"; amount?: number; currency?: string; customerEmail?: string };
export default function OrderConfirmationPage() { return <Suspense fallback={<StateCard title="Checking payment status…" detail="Loading your order." />}><OrderConfirmationContent /></Suspense>; }
function OrderConfirmationContent() {
  const params = useSearchParams(); const orderId = params.get("orderId"); const [order, setOrder] = useState<Confirmation | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!orderId) return; fetch(`/api/orders/${orderId}`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not load order"); return body; }).then(setOrder).catch((err) => setError(err instanceof Error ? err.message : "Could not load order")); }, [orderId]);
  if (!orderId) return <StateCard title="Order reference missing" detail="Return to your cart and try again." actionHref="/cart" actionLabel="Back to cart" />;
  if (error) return <StateCard title="We could not load your order" detail={error} actionHref="/cart" actionLabel="Back to cart" />;
  if (!order) return <StateCard title="Checking payment status…" detail={`Order ${orderId}`} />;
  if (order.paymentStatus === "COMPLETED" && order.orderStatus === "paid") return <StateCard success title="Payment successful" detail={`Thank you for your order. Your order is confirmed.${order.customerEmail ? ` A receipt can be sent to ${order.customerEmail}.` : ""}`} order={order} actionHref="/products" actionLabel="Continue shopping" />;
  if (order.paymentStatus === "FAILED" || order.orderStatus === "payment_failed") return <StateCard title="Payment failed" detail="Your order has not been paid. No paid order has been recorded. You can safely retry the payment." order={order} actionHref="/checkout" actionLabel="Retry payment" />;
  if (order.paymentStatus === "CANCELLED" || order.orderStatus === "cancelled") return <StateCard title="Payment cancelled" detail="The payment was cancelled and your order is not marked as paid." order={order} actionHref="/checkout" actionLabel="Try again" />;
  return <StateCard title="Payment pending" detail="We are waiting for payment confirmation." order={order} actionHref={`/order-confirmation?orderId=${order.orderId}`} actionLabel="Refresh status" />;
}
function StateCard({ title, detail, order, actionHref, actionLabel, success = false }: { title: string; detail: string; order?: Confirmation; actionHref?: string; actionLabel?: string; success?: boolean }) { return <main><section className="mx-auto max-w-3xl px-5 py-16 text-center md:px-8 md:py-24"><div className={`mx-auto flex h-16 w-16 items-center justify-center rounded-full ${success ? "bg-[#dce8df] text-[#173f35]" : "bg-[#efeee8] text-stone-700"} text-2xl`} aria-hidden="true">{success ? "✓" : "·"}</div><p className="mt-7 text-xs font-semibold uppercase tracking-[0.2em] text-[#47655d]">Order confirmation</p><h1 className="mt-3 text-4xl font-medium tracking-tight md:text-5xl">{title}</h1><p className="mx-auto mt-5 max-w-xl leading-7 text-stone-600">{detail}</p>{order && <div className="mx-auto mt-8 max-w-lg rounded-[20px] border border-stone-200 bg-white p-6 text-left text-sm"><div className="flex justify-between gap-4"><span className="text-stone-500">Order number</span><strong>{order.orderId}</strong></div>{order.amount !== undefined && <div className="mt-3 flex justify-between"><span className="text-stone-500">Total</span><strong>{order.amount} {order.currency ?? "SEK"}</strong></div>}<div className="mt-3 flex justify-between"><span className="text-stone-500">Payment</span><strong>{order.paymentStatus}</strong></div></div>}{actionHref && actionLabel && <div className="mt-8 flex justify-center gap-3"><Link href={actionHref} className="rounded-full bg-[#173f35] px-6 py-3.5 text-sm font-semibold text-white">{actionLabel}</Link><Link href="/" className="rounded-full border border-stone-300 px-6 py-3.5 text-sm font-semibold">Home</Link></div>}</section><TrustStrip /></main>; }
